# Generated by Django 5.2.14 on 2026-05-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("issuing_organization", models.CharField(blank=True, max_length=180)),
                ("version", models.CharField(blank=True, max_length=40)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("target_level", models.CharField(blank=True, max_length=20)),
                ("scope", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GradingDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=80, unique=True)),
                ("name_fr", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("applies_to", models.JSONField(blank=True, default=list)),
                ("weight_hint", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_source", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["source_id"],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_path", models.CharField(max_length=500)),
                ("source_hash", models.CharField(blank=True, max_length=128)),
                ("source_version", models.CharField(blank=True, max_length=40)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("created_counts", models.JSONField(blank=True, default=dict)),
                ("updated_counts", models.JSONField(blank=True, default=dict)),
                ("skipped_counts", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("dry_run", models.BooleanField(default=False)),
                ("replace_existing", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("oral", "Oral"),
                            ("written", "Written"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["source_id"],
            },
        ),
        migrations.CreateModel(
            name="ExamSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=80, unique=True)),
                ("name_fr", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("sequence_order", models.PositiveSmallIntegerField()),
                (
                    "total_duration_minutes",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "preparation_time_minutes",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("format", models.TextField(blank=True)),
                ("number_of_tasks", models.PositiveSmallIntegerField(default=0)),
                ("section_notes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_source", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LevelDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("description", models.TextField()),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_descriptors",
                        to="exams.gradingdimension",
                    ),
                ),
            ],
            options={
                "ordering": ["dimension__source_id", "level"],
            },
        ),
        migrations.CreateModel(
            name="ScoreBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("score_min", models.DecimalField(decimal_places=1, max_digits=4)),
                ("score_max", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "midpoint",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_bands",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["score_min"],
            },
        ),
        migrations.CreateModel(
            name="TaskDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=80, unique=True)),
                ("task_number", models.PositiveSmallIntegerField()),
                ("name_fr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("format", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "suggested_duration_minutes",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "preparation_time_minutes",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "word_count_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "word_count_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "word_count_target",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "expected_response_word_count_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "expected_response_word_count_ideal",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "expected_response_word_count_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("expected_structure", models.JSONField(blank=True, default=list)),
                ("required_elements", models.JSONField(blank=True, default=list)),
                ("skills_assessed", models.JSONField(blank=True, default=list)),
                ("strategy_tips", models.JSONField(blank=True, default=list)),
                ("common_pitfalls", models.JSONField(blank=True, default=list)),
                ("common_topics", models.JSONField(blank=True, default=list)),
                ("examiner_behavior", models.TextField(blank=True)),
                ("rubric_dimensions", models.JSONField(blank=True, default=list)),
                ("task_specific_rubric", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_source", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_definitions",
                        to="exams.examsection",
                    ),
                ),
            ],
            options={
                "ordering": ["task_number"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=80, unique=True)),
                ("section_source_id", models.CharField(max_length=80)),
                ("task_number", models.PositiveSmallIntegerField()),
                ("task_type_fr", models.CharField(max_length=160)),
                ("prompt", models.TextField()),
                ("themes", models.JSONField(blank=True, default=list)),
                ("timing", models.JSONField(blank=True, default=dict)),
                ("addressee", models.CharField(blank=True, max_length=120)),
                ("register", models.CharField(blank=True, max_length=160)),
                ("channel", models.CharField(blank=True, max_length=160)),
                ("examiner_role_fr", models.CharField(blank=True, max_length=160)),
                ("expected_response", models.JSONField(blank=True, default=dict)),
                ("evaluation_focus", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_source", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.taskdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["task_number", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="TestDefinitionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_order", models.PositiveSmallIntegerField()),
                (
                    "task_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_steps",
                        to="exams.taskdefinition",
                    ),
                ),
                (
                    "test_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="exams.testdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["test_definition__source_id", "sequence_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="examsection",
            constraint=models.UniqueConstraint(
                fields=("exam", "sequence_order"), name="unique_section_order_per_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="leveldescriptor",
            constraint=models.UniqueConstraint(
                fields=("dimension", "level"), name="unique_descriptor_per_dimension"
            ),
        ),
        migrations.AddConstraint(
            model_name="scoreband",
            constraint=models.UniqueConstraint(
                fields=("exam", "level"), name="unique_score_band"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdefinition",
            constraint=models.UniqueConstraint(
                fields=("section", "task_number"), name="unique_task_number_per_section"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["section_source_id", "task_number", "is_active"],
                name="exams_quest_section_428f07_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="testdefinitionstep",
            constraint=models.UniqueConstraint(
                fields=("test_definition", "sequence_order"),
                name="unique_step_order_per_test_definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="testdefinitionstep",
            constraint=models.UniqueConstraint(
                fields=("test_definition", "task_definition"),
                name="unique_task_per_test_definition",
            ),
        ),
    ]
