# Generated by Django 5.2.14 on 2026-05-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("prompt_markdown", models.TextField(blank=True)),
                ("candidate_input", models.TextField(blank=True)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("response_id", models.CharField(blank=True, max_length=120)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("parsed_result", models.JSONField(blank=True, default=dict)),
                (
                    "overall_score_20",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("estimated_cefr_level", models.CharField(blank=True, max_length=10)),
                ("automatic_failure", models.BooleanField(default=False)),
                (
                    "automatic_failure_reasons",
                    models.JSONField(blank=True, default=list),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="simulations.taskattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
