# Generated by Django 5.2.14 on 2026-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgrade",
            name="audio_feedback",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="taskgrade",
            name="audio_feedback_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="taskgrade",
            name="audio_feedback_status",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
