# Generated by Django 5.2.14 on 2026-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_taskgrade_audio_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgrade",
            name="improved_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="taskgrade",
            name="improved_response_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="taskgrade",
            name="improved_response_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="taskgrade",
            name="improved_response_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="taskgrade",
            name="improved_response_status",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
