# Generated by Django 5.2.14 on 2026-05-10 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("mode", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("grading", "Grading"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_step_order", models.PositiveSmallIntegerField(default=1)),
                ("random_seed", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "oral_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("oral_level", models.CharField(blank=True, max_length=10)),
                (
                    "written_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("written_level", models.CharField(blank=True, max_length=10)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="exams.testdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "task_definition_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("question_snapshot", models.JSONField(blank=True, default=dict)),
                ("sequence_order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("grading", "Grading"),
                            ("graded", "Graded"),
                            ("grading_failed", "Grading failed"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_late", models.BooleanField(default=False)),
                ("answer_text", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, upload_to="oral_recordings/%Y/%m/%d/"),
                ),
                ("audio_mime_type", models.CharField(blank=True, max_length=120)),
                ("transcript_text", models.TextField(blank=True)),
                ("manual_transcript", models.BooleanField(default=False)),
                (
                    "word_count_observed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("within_word_limits", models.BooleanField(blank=True, null=True)),
                ("client_events", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="exams.question",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="exams.testdefinitionstep",
                    ),
                ),
                (
                    "test_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="simulations.testsession",
                    ),
                ),
            ],
            options={
                "ordering": ["test_session", "sequence_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("test_session", "sequence_order"),
                        name="unique_attempt_order_per_session",
                    )
                ],
            },
        ),
    ]
